# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder
      - elbow
      - pitch
      - roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      # - velocity
    open_loop_control: false 
    
gripper_controller:
  ros__parameters:
    joint: finger_L_joint
    goal_tolerance: 0.01
    stalled_velocity_threshold: 0.01
    stall_timeout: 0.2