# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - hand_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - base_joint
      - elbow
      - shoulder
      - pitch
      - roll
  hand_controller:
    type: GripperCommand
    joints:
      - finger_L_joint
    action_ns: gripper_cmd
    default: true