controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# aca esta mal las juntas del gripper no van las dos y ademas van en action gripper
joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_joint
      - elbow
      - shoulder
      - pitch
      - roll
      - finger_R_joint
      - finger_L_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity