# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      pid:
        p: 100
        i: 10


    gripper_controller:
      type: position_controllers/GripperActionController
      # pid:
      #   p: 10
      #   i: 0.02
      #   d: 0.0

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - shoulder
      - elbow
      - pitch
      - roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
gripper_controller:
  ros__parameters:
    joint: finger_L_joint