# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    #use_sim_time : true #el tipo hace esto, pero no explica el pq

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    hand_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - base_joint
      - elbow
      - shoulder
      - pitch
      - roll
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
   # use_stamp_vel : false #el tipo hace esto, pero no explica el pq
hand_controller:
  ros__parameters:
    joint: finger_L_joint